name: aliyun_saf
description: SAF HTTPS plugin for Aliyun.
version: 0.2.0
# author: https://github.com/AlexV525
homepage: https://github.com/AlexV525/flutter_aliyun_saf

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  crypto: ^3.0.1
  flutter:
    sdk: flutter
  http: ^0.13.2
  uuid: ^3.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.alexv525.aliyun_saf
        pluginClass: AliyunSAFPlugin